# Generated by Django 3.0.6 on 2020-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlie', '0002_synthesizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthesizer',
            name='export_audio',
            field=models.FileField(blank=True, upload_to='machine_voice'),
        ),
    ]
